# Generated by Django 3.0 on 2024-08-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('short_title', models.CharField(max_length=100)),
                ('description_short', models.CharField(max_length=500)),
                ('description_long', models.TextField()),
                ('coord_lng', models.FloatField()),
                ('coord_lat', models.FloatField()),
                ('show_coord_lng', models.FloatField()),
                ('show_coord_lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.ImageField(upload_to='img/')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
